### ISSUE TITLE
Installing Lean on Ubuntu.

### ISSUE THREAD

**Issue by anaslasri** [ImperialCollegeLondon/xena-UROP-2018#9]
Hi there,
I tried installing Lean on the latest version of Ubuntu with the help of [https://xenaproject.wordpress.com/2017/12/02/how-to-install-mathlib-and-keep-it-up-to-date/](url). However when I try the last step in the command line to check the version of Lean that I have I get the error message: Lean: command not found. Can anyone think of something that might have gone wrong?
Thanks,
Anas

**Comment by kbuzzard** [comment]
You need to fix your path variable.
